version: "3"

services:
  utilityapi:
    image: utilityapi:dev
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.dev.amd64
    container_name: utilityapi
    ports:
      - 3500:3500
    volumes:
      - ../src:/app/src
      - ../modules:/app/modules
    environment:
      - PORT=3500
      - PGID=1000
      - PUID=1000
      - GENIUS_ACCESS_TOKEN=${GENIUS_ACCESS_TOKEN}
    restart: always