FROM node:lts-slim AS development
LABEL maintainer="Arville"

ENV PORT=3500
ENV PGID=1000
ENV PUID=1000
ENV NODE_ENV=development
ENV GENIUS_ACCESS_TOKEN=

WORKDIR /app

# Cache and Install dependencies
COPY package.json .
COPY package-lock.json .
RUN npm install

# Copy app files
COPY . .

# Install Puppeteer dependency
RUN apt-get update \
    && apt-get install -y wget gnupg \
    && wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
    && sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' \
    && apt-get update \
    && apt-get install -y google-chrome-stable fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst fonts-freefont-ttf libxss1 \
    --no-install-recommends \
    && rm -rf /var/lib/apt/lists/*

RUN chown ${PUID}:${PGID} -R /app

VOLUME [ "/app/src", "/app/modules" ]
EXPOSE 3500

USER ${PUID}:${PGID}

CMD ["npm", "run", "test"]